name: Windows RDP 7h

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 420

    steps:
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set Password
      run: net user runneradmin YourPassword123

    - name: Start RDP Session
      run: |
        Invoke-WebRequest https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWInst-v1.6.2.zip -OutFile RDPWInst.zip
        Expand-Archive RDPWInst.zip -DestinationPath RDPW
        cd RDPW
        .\install.bat
        .\RDPConf.exe

    - name: Done
      run: Write-Output "RDP is ready. Use IP:port and username: runneradmin"
